[project]
name = "neumann4"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.2",
    "openai>=2.1.0",
    "pillow>=11.3.0",
    "pymupdf>=1.26.4",
]
